### PR TITLE
Adds support for slide-page-screen abstraction

### PR DESCRIPTION
**Pull request by danielsson**
This PR enables users to create slides with several pages, as discussed in #39 
Also, the PR solves some other small issues.

What this PR does not do is to provide a *good* looking UI; that is left for the future.

### CODE REVIEW

**Comment by danielsson** [comment]
Also, now those annoying scroll bars should be fixed

**Comment by Plongy** [comment]
Needs work on GUI and it breaks history.

We could live without history, but yeah...

On the note of GUI:
<ul>
 <li>It's not intuitive at all...</li>
 <li>The add slide shows even when you aren't logged in</li>
 <li>It's not intuitive at all...</li>
 <li>It's not intuitive at all...</li>
</ul>

**Comment by danielsson** [comment]
Perhaps we could just add a small descriptive text before the ui to make it more clear, until we build a better ui?

**Comment by danielsson** [comment]
@Plongy :+1: LGTM

**Pull request merged**
