### PR TITLE
some fixes and usability improvements

### PR DESCRIPTION
**Pull request by JSimo**

### CODE REVIEW

**Comment by aronstrandberg** [comment]
:+1:

**Comment by JSimo** [comment]
Some features suggested in #66 got implemented.

**Comment by aronstrandberg** [comment]
:+1: :+1: :+1: Looks good to me, but wouldn't hurt if perhaps @decentninja or @danielsson took a peek.

**Comment by JSimo** [comment]
there is currently one bug that needs to be fixed before merging, editing the date when it is set to Never expire and just directly saving causes it to be saved as 1970-01-01.

**Pull request merged**
