### PR TITLE
Fix arbitrary file incusion

### PR DESCRIPTION
**Pull request by mathiasmagnusson**
Maybe it isn't a great idea to let anyone read or write any file that this project has access to :)

### CODE REVIEW

**Comment by Herkarl** [comment]
Nice! :+1:

**Comment by movitz-s** [comment]
:eyes:

**Comment by Herkarl** [comment]
Seems to be broke tho :cry:

**Comment by Herkarl** [comment]
Log extract @mathiasmagnusson 

```2022-11-08T14:49:42.315251773Z app[web.1]: Error: ENOENT, no such file or directory '../../../../../uploaded/mitten1-klar.jpg1667918966622'
2022-11-08T14:49:42.315254947Z app[web.1]:     at Object.fs.openSync (fs.js:439:18)
2022-11-08T14:49:42.315258048Z app[web.1]:     at Object.fs.readFileSync (fs.js:290:15)
2022-11-08T14:49:42.315261210Z app[web.1]:     at [object Object].route.action (app/server/fileupload.js:16:18)
2022-11-08T14:49:42.315264570Z app[web.1]:     at boundNext (packages/iron_middleware-stack.js:408:31)
2022-11-08T14:49:42.315267681Z app[web.1]:     at runWithEnvironment (packages/meteor.js:1154:24)
2022-11-08T14:49:42.315270825Z app[web.1]:     at packages/meteor.js:1167:14
2022-11-08T14:49:42.315273924Z app[web.1]:     at [object Object].urlencodedParser (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/iron_router/node_modules/body-parser/lib/types/urlencoded.js:84:40)
2022-11-08T14:49:42.315277399Z app[web.1]:     at packages/iron_router.js:885:36
2022-11-08T14:49:42.315280447Z app[web.1]:     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
2022-11-08T14:49:42.315283602Z app[web.1]:     at [object Object].hookWithOptions (packages/iron_router.js:884:27)
2022-11-08T14:49:42.327992132Z app[web.1]: Error: ENOENT, no such file or directory '../../../../../uploaded/mitten1-klar.jpg1667918966622'
2022-11-08T14:49:42.328021223Z app[web.1]:     at Object.fs.openSync (fs.js:439:18)
2022-11-08T14:49:42.328025333Z app[web.1]:     at Object.fs.readFileSync (fs.js:290:15)
2022-11-08T14:49:42.328028896Z app[web.1]:     at [object Object].route.action (app/server/fileupload.js:16:18)
2022-11-08T14:49:42.328032502Z app[web.1]:     at boundNext (packages/iron_middleware-stack.js:408:31)
2022-11-08T14:49:42.328035913Z app[web.1]:     at runWithEnvironment (packages/meteor.js:1154:24)
2022-11-08T14:49:42.328039235Z app[web.1]:     at packages/meteor.js:1167:14
2022-11-08T14:49:42.328042608Z app[web.1]:     at [object Object].urlencodedParser (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/iron_router/node_modules/body-parser/lib/types/urlencoded.js:84:40)
2022-11-08T14:49:42.328062561Z app[web.1]:     at packages/iron_router.js:885:36
2022-11-08T14:49:42.328066518Z app[web.1]:     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
2022-11-08T14:49:42.328069805Z app[web.1]:     at [object Object].hookWithOptions (packages/iron_router.js:884:27)```

**Pull request merged**
